# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: UTC

# jekyll-seo-tag settings
# ↓ --------------------------

title: Slifer0's Cyber Fort  # the main title

tagline: Exploring the depths of cybersecurity and ethical hacking. # subtitle reflecting your field

description: >-
  A blog dedicated to penetration testing, cybersecurity research, and hacking tutorials. Follow Slifer0 on his journey to uncover vulnerabilities and improve security practices.

# Site URL
url: "https://slifer0.github.io"  # your GitHub Pages URL (without the trailing slash)

github:
  username: Slifer0  # change to your GitHub username

twitter:
  username: Slifer0  # change to your Twitter username (if you have one)

social:
  name: Slifer0  # your hacking name
  email: slifer0@example.com # your email address
  links:
    - https://twitter.com/Slifer0  # your Twitter homepage
    - https://github.com/Slifer0  # your GitHub homepage
    # Uncomment below to add more social links
    # - https://www.linkedin.com/in/slifer0

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code

# ↑ --------------------------
# End of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: # your Google Analytics ID
  goatcounter:
    id: # your GoatCounter ID

# Page views settings
pageviews:
  provider: goatcounter  # Page view analytics, use GoatCounter as an example

# Prefer color scheme
theme_mode: dark  # default to dark mode for a "hacker" feel

# CDN endpoint for media resources
cdn:

# Avatar on sidebar
avatar: /assets/slifer-the-sky-dragon-yu-gi-oh-wallpaper-preview.jpg  # example, replace with your image path

# Social preview image used in SEO meta tag
social_preview_image: /assets/images/social-preview.png

# Enable table of contents for all posts
toc: true

# Comments
comments:
  provider: giscus  # Enable comments using Giscus
  giscus:
    repo: Slifer0/Slifer0.github.io  # your GitHub repo for comments
    repo_id: your_repo_id  # fill with your repo ID
    category: General
    category_id: your_category_id
    lang: en

# Self-hosted static assets (optional)
assets:
  self_host:
    enabled: false

# PWA (Progressive Web App) settings
pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10  # Show 10 posts per page

# Base URL of your site
baseurl: ""

# Kramdown configuration for Markdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true

# Collections settings
collections:
  tabs:
    output: true
    sort_by: order

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
